### ISSUE TITLE
androsc.omm not converting sliders and pads to midi

### ISSUE THREAD

**Issue by rghvdberg** [ssj71/OSC2MIDI#20]
run osc2mid  -m androsc.omm -v
run AndrOSC on android devive
on device open template3
only some buttons generate midi messages, sliders don't translate to midi

running osc2mid -mon shows osc messages (sliders, buttons) etc coming in

**Comment by rghvdberg** [comment]
Upon further investigation it look like AndrOSC send the sliders as type 's' (is this strings?)

**Comment by ssj71** [comment]
ok. I'm changing that mapping, but you should know that all 3 of the included templates are fairly useless until you change the osc path for each control (i.e. all the sliders, buttons, pads all send the same message). As soon as you change that path, the mapping isn't valid any longer. But it should do something out of the box (even if its not very useful). Now it does.

Thanks for the report!

**Comment by rghvdberg** [comment]
still doesn't work
this is the output of osc2midi -m androsc -v -mon

> Monitor mode, incoming OSC messages will only be printed.
> starting osc server on port 57120
> Ready.
> /vslider s, "0,062"
> /vslider s, "0,071"
> /vslider s, "0,092"
> /vslider s, "0,131"
>    ....... etc etc 
> /vslider s, "0,985"
> /vslider s, "0,996"
> /vslider i, 1
> /vslider i, 1
> /vslider i, 1
> /vslider i, 1
> /vslider s, "0,994"
> /vslider s, "0,971"
> /vslider s, "0,94"
> /vslider s, "0,912"
> /vslider s, "0,888"
> /vslider s, "0,867"
> /vslider s, "0,844" 
> ...... etc etc
> /vslider s, "0,023"
> /vslider s, "0,002"
> /vslider i, 0
> quitting...
> closing osc server

**Comment by agraef** [comment]
Well, the OSC2MIDI map is just an example; you'll have to modify it yourself to match whatever AndrOSC template you use on the device. Also, note that the present version of OSC2MIDI doesn't handle string values ('s' type), such messages will be ignored. So you'll have to modify your AndrOSC template so that it emits floats or doubles ('f' or 'd' type) instead. I'm not familiar with AndrOSC, so I don't know whether that is possible; if AndrOSC insists on emitting slider values as strings (I'd consider that a bug) then you're out of luck -- but Google Play has other OSC apps like Control and TouchOSC on offer which will encode slider values as floats.

If you need some information about OSC2MIDI's map file format, I've written up some documentation in Markdown format for my students. This isn't quite finished yet, but may still be helpful. For the time being, you can find it here: https://www.dropbox.com/s/5cdhsgk5ekl3xg6/syntax.md?dl=0

**Comment by ssj71** [comment]
I notice the strings are using a comma ',' instead of a decimal '.' so perhaps this is an android system setting that is making androsc interpret the numbers as strings. Looking at this comment: https://github.com/artsince/AndrOSC/issues/6#issuecomment-61591457 from androsc's bug tracking it looks like you aren't the only one with the issue.  It seems development on androsc has stopped for about a year.
Can you try setting the language to English and see if that makes a difference? If that's not acceptable I'd recommend you try the also free and open source app "Control (midi + osc)" also known as Charlie's Control. I use it primarily.

**Comment by rghvdberg** [comment]
Yeah, , I too figured out that AndrOSC is a dead project. Let's not waste
anymore time on this.

I'm going for Control.

Thanks for the help.
Op 30 jul. 2015 18:47 schreef "ssj71" notifications@github.com:

**Comment by ssj71** [comment]
just a note, Control is also a dead project and has some obnoxious but workable bugs. It seems no open source android OSC project is able to generate enough interest to keep development going. I've looked through the source of both a little and can't make much heads or tails of them to try to fix the issues I've seen.

**Comment by rghvdberg** [comment]
So, let's make our own Android app. InfamousOSC!
Op 30 jul. 2015 18:54 schreef "ssj71" notifications@github.com:

**Comment by ssj71** [comment]
just FYI I've now added the Control interfaces so they can be accessed through http://ssj71.github.io/OSC2MIDI/interfaces/gen_synth_phone.js
(This is also documented in the readme). If you make any more useful interfaces I'd love to include them as well.
